server:
  port: 8085


spring:
  application:
    name: API-SERVER


  cloud:
    gateway:
      routes:
        - id: USER-SERVER
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**

        -  id : HOTEL-SERVER
           uri: lb://HOTEL-SERVER
           predicates:
             - Path=/hotel/**

        - id: RATING-SERVER
          uri: lb://RATING-SERVER
          predicates:
            - Path=/rating/**
  config:
    import:
      - configserver:http://localhost:8086






