server:
  port: 8085


spring:
  application:
    name: API-SERVER


  cloud:
    gateway:
      routes:
        - id: USER-SERVER
          uri: lb://USER-SERVER
          predicates:
            - Path=/user/**


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

    service-url:
      defaultZone: http://localhost:5761/eureka/



