
server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: ratingDb
  application:
    name: rating-Server

eureka:


  client:
    service-url:
      defaultZone: http://localhost:5761/eureka/
    fetch-registry: true
    register-with-eureka: true
