

server:
  port: 8080



spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/microserice
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

    show-sql: true


eureka:
  instance:
    hostname: User-server

  client:
    fetch-registry: true

    register-with-eureka: true

    service-url:
      defaultZone :  http://localhost:5761/eureka/


