

server:
  port: 8080



spring:
  application:
    name: USER-SERVER
  datasource:
    url: jdbc:mysql://localhost:3306/microserice
    username: root
    password: root
    driver-class-name:  com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

    show-sql: true
  config:
    import:
      - configserver:http://localhost:8086


resilience4j:
  circuitbreaker:
    instances:
      GetAllUserCircuitBraker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        registerHealthIndicator: true
        permittedNumberOfCallsInHalfOpenState: 2
        automaticTransitionFromOpenToHalfOpenEnabled: true
        maxWaitDurationInHalfOpenState: 2
        minimumNumberOfCalls: 3

management:
  endpoint:
    health:
      show-details: ALWAYS
      enabled: true






